<a href="https://colab.research.google.com/github/hurileborjigin/pytorch_notes/blob/main/autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Autograd

In [1]:
import torch


# Creating a tensor with grad
weights = torch.ones(4, requires_grad=True)
weights

tensor([1., 1., 1., 1.], requires_grad=True)

In [2]:
for epoch in range(3):
  model_output = (weights*3).sum()


  model_output.backward()
  print(weights.grad)

  weights.grad.zero_()






tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [3]:

optimizer = torch.optim.SGD([weights], lr=0.01)
optimizer.step()
optimizer.zero_grad()

In [4]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

## Back propagation

In [9]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)


# Forward pass and compute loss
y_hat = w * x
loss = (y_hat - y)**2

print(loss)

# backward pass
loss.backward()
print(w.grad)


# Update weights and next forward pass and backward pass


tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


## Gradients

In [3]:
import numpy as np
import torch

In [19]:
# f = w * x

# f = 2 * x
X = np.array([1, 2, 3, 4], dtype=np.float32)
Y = np.array([2, 4, 6, 8], dtype=np.float32)


w = 0.0

# model prediction
def forward(x):
  return w * x


# loss MSE
def loss(y, y_pred):
  return ((y_pred - y) ** 2).mean()


# gradient
# MSE = 1/n(w*x - y)**2

# dJ/dw = 1/n * 2x * (wx-y)
def gradient(x, y, y_pred):
  return np.dot(2*x, y_pred-y).mean()

print(f'Prediction before training: f(5) = {forward(5):3f}')


# Define training
lr = 0.01
iter_num = 100

for i in range(iter_num):
  # Prediction = forward_pass(x)
  y_pred = forward(X)
  losses = loss(Y, y_pred)

  dw = gradient(X, Y, y_pred)

  w = w - lr * dw

  if i % 10 == 0:
    print(f'epoch {i+1}: w = {w:.3f}, loss = {losses:.8f}')

print(f'Prediction after training: f(5) = {forward(5):3f}')

Prediction before training: f(5) = 0.000000
epoch 1: w = 1.200, loss = 30.00000000
epoch 11: w = 2.000, loss = 0.00000033
epoch 21: w = 2.000, loss = 0.00000000
epoch 31: w = 2.000, loss = 0.00000000
epoch 41: w = 2.000, loss = 0.00000000
epoch 51: w = 2.000, loss = 0.00000000
epoch 61: w = 2.000, loss = 0.00000000
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000000


In [5]:
# f = w * x

# f = 2 * x
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)


w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

# model prediction
def forward(x):
  return w * x


# loss MSE
def loss(y, y_pred):
  return ((y_pred - y) ** 2).mean()



print(f'Prediction before training: f(5) = {forward(5):3f}')


# Define training
lr = 0.01
iter_num = 100

for i in range(iter_num):
  # Prediction = forward_pass(x)
  y_pred = forward(X)
  l = loss(Y, y_pred)

  # gradient. dl/dw
  l.backward()

  with torch.no_grad():
    w -= lr * w.grad

  w.grad.zero_()
  if i % 10 == 0:
    print(f'epoch {i+1}: w = {w:.3f}, loss = {l:.8f}')

print(f'Prediction after training: f(5) = {forward(5):3f}')

Prediction before training: f(5) = 0.000000
epoch 1: w = 0.300, loss = 30.00000000
epoch 11: w = 1.665, loss = 1.16278565
epoch 21: w = 1.934, loss = 0.04506890
epoch 31: w = 1.987, loss = 0.00174685
epoch 41: w = 1.997, loss = 0.00006770
epoch 51: w = 1.999, loss = 0.00000262
epoch 61: w = 2.000, loss = 0.00000010
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 9.999998
